<a href="https://colab.research.google.com/github/pablex72/numpy-panda/blob/main/Managing_null_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dict = {'Col1' : [1,2,3,np.nan],
        'Col2' : [4,np.nan,6,7],
        'Col3' : ['a','b','c', None]
}

In [4]:
df = pd.DataFrame(dict)

In [5]:
df.isnull()

    Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [6]:
df.isnull() * 1

   Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [7]:
df.fillna('Missing')

      Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [8]:
df.fillna(df.mean())

<ipython-input-8-a2478f315f9e>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())

   Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [9]:
#hace una interpolacion de la serie asumiendo cual es el valor que deberia seguir
df.interpolate()

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [10]:
df.dropna()

   Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c